# usod10k dataset with Franca Large Laion
dataset: "usod10k"
model: "upernet_franca_large_laion_no_rasa"

data_root: "/workspace/data"
batch_size: 90
epochs: 100
lr: 1e-4
weight_decay: 1e-4

scheduler: "cosine"
warmup_epochs: 0
augmentation: "heavy"
freeze_backbone: true
gpus: "0"
precision: "bf16-mixed"
num_workers: 8
wandb_project: "UnderwaterBenchmark"
experiment_name: "franca_large_laion"
log_dir: "/workspace/logs"
hf_login: true
