# cou dataset with Dinov3 Base (Linear Probing)
dataset: "cou"
model: "linear_dinov3_base"

data_root: "/workspace/data"
batch_size: 90
epochs: 20
lr: 1e-4
weight_decay: 1e-4

scheduler: "cosine"
warmup_epochs: 0
augmentation: "heavy"
freeze_backbone: true
gpus: "0"
precision: "bf16-mixed"
num_workers: 8
wandb_project: "UnderwaterBenchmark"
experiment_name: "_"
log_dir: "/workspace/logs"
hf_login: true
