# seaclear_sup dataset with ResNet-50
dataset: "seaclear_sup"
model: "upernet_resnet50"

data_root: "/workspace/data"
batch_size: 15
epochs: 100
lr: 1e-4
weight_decay: 1e-4

scheduler: "cosine"
warmup_epochs: 0
augmentation: "heavy"
freeze_backbone: false
gpus: "0"
precision: "bf16-mixed"
num_workers: 2
wandb_project: "UnderwaterBenchmark"
experiment_name: "_"
log_dir: "/workspace/logs"
hf_login: false
