# seaclear_mat dataset with Radio V4 SO400M (Last Layer)
dataset: "seaclear_mat"
model: "upernet_radio_v4_so400m_lastlayer"

data_root: "/workspace/data"
batch_size: 50
epochs: 100
lr: 1e-4
weight_decay: 1e-4

scheduler: "cosine"
warmup_epochs: 0
augmentation: "heavy"
freeze_backbone: true
gpus: "0"
precision: "bf16-mixed"
num_workers: 2
wandb_project: "UnderwaterBenchmark"
experiment_name: "_"
log_dir: "/workspace/logs"
hf_login: true
