# trashcan_material dataset with Dinov3 Base (Last Layer)
dataset: "trashcan_material"
model: "upernet_dinov3_base_lastlayer"

data_root: "/workspace/data"
batch_size: 90
epochs: 100
lr: 1e-4
weight_decay: 1e-4

scheduler: "cosine"
warmup_epochs: 0
augmentation: "heavy"
freeze_backbone: true
gpus: "0"
precision: "bf16-mixed"
num_workers: 8
wandb_project: "UnderwaterBenchmark"
experiment_name: "_"
log_dir: "/workspace/logs"
hf_login: true
