# usod10k dataset with ResNet-101
dataset: "usod10k"
model: "upernet_resnet101"

data_root: "/workspace/data"
batch_size: 20
epochs: 100
lr: 1e-4
weight_decay: 1e-4

scheduler: "cosine"
warmup_epochs: 0
augmentation: "heavy"
freeze_backbone: false
gpus: "0"
precision: "bf16-mixed"
num_workers: 8
wandb_project: "UnderwaterBenchmark"
experiment_name: "_"
log_dir: "/workspace/logs"
hf_login: false
